### ISSUE TITLE
[Bug] Monorepo setup build failure

### ISSUE THREAD

**Issue by spatialvlad** [ammarahm-ed/react-native-mmkv-storage#165]
**Describe the bug**
I run my RN project in a monorepo type of setup, where mobile is only one of the packages, with the shared `node_modules` folder being several folders above in the folders tree.
The setup is similar to this one: https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej
Though most other monorepo setups, e.g. using lerna, would also be structured similarly.

My `react-native-mmkv-storage` version is `0.6.3`, i also have `react-native-reanimated` v2, follows the instructions on how to setup Android.

When I try to build the project on Android I get an error:

```
* Where:
Build file '/home/mylaptop/Code/myproject/node_modules/react-native-mmkv-storage/android/build.gradle' line: 84

* What went wrong:
A problem occurred evaluating project ':react-native-mmkv-storage'.
> Expected directory '/home/mylaptop/Code/myproject/packages/mobile/android/../node_modules/react-native/android' to contain exactly one file, however, it contains no files.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mylaptop/Code/myproject/node_modules/react-native-mmkv-storage/android/build.gradle' line: 84

* What went wrong:
A problem occurred evaluating project ':react-native-mmkv-storage'.
> Expected directory '/home/mylaptop/Code/myproject/packages/mobile/android/../node_modules/react-native/android' to contain exactly one file, however, it contains no files.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s

    at makeError (/home/mylaptop/Code/myproject/node_modules/execa/index.js:174:9)
    at /home/mylaptop/Code/mylaptop/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/mylaptop/Code/myproject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/home/mylaptop/Code/myproject/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/mylaptop/.nvm/versions/node/v16.9.1/bin/node
Arguments: /home/mylaptop/.yarn/lib/cli.js run android
Directory: /home/mylaptop/Code/myproject/packages/mobile
Output:
```

I looked at the issues in this repo and did not find anything related, but looking at a somewhat similar library `react-native-mmkv` I found a similar issue:
https://github.com/mrousavy/react-native-mmkv/issues/148
And related PR to fix it:
https://github.com/mrousavy/react-native-mmkv/pull/151/files

**To Reproduce**
1. Have monorepo-type project setup, with `node_modules` being hosted several folders up in the project hierarchy
2. Try to follow instructions for Android

**Expected behavior**
The library works with monorepo setup. Or at a minimum, some workaround with instructions on how to address the issue is provided.

**Platform Information:**
 - OS: Android
 - React Native Version 0.65
 - Library Version 0.6.3

Thank you for the great library.

**Comment by ammarahm-ed** [comment]
@spatialvlad I will fix this today

**Comment by ammarahm-ed** [comment]
Fixed on master  @spatialvlad , test with

```
yarn add https://github.com/ammarahm-ed/react-native-mmkv-storage.git
```
and let me know.

**Comment by spatialvlad** [comment]
@ammarahm-ed ,

Thanks for a prompt turnaround.

I see that it does go further in the build process. But unfortunately in my case it the build still fails. Here is the error message:

```
> Task :react-native-mmkv-storage:externalNativeBuildDebug
Build rnmmkv_armeabi-v7a
ninja: Entering directory `/home/mylaptop/Code/myproject/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/armeabi-v7a'
Build rnmmkv_arm64-v8a
ninja: Entering directory `/home/mylaptop/Code/myproject/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/arm64-v8a'
Build rnmmkv_x86
ninja: Entering directory `/home/mylaptop/Code/myproject/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/x86'
Build rnmmkv_x86_64
ninja: Entering directory `/home/mylaptop/Code/myproject/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/x86_64'

> Task :app:mergeDebugNativeLibs FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
292 actionable tasks: 5 executed, 287 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/x86_64/libreactnativejni.so'.
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'lib/x86_64/libreactnativejni.so'.
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

    at makeError (/home/mylaptop/Code/myproject/node_modules/execa/index.js:174:9)
    at /home/mylaptop/Code/myproject/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/mylaptop/Code/myproject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/home/mylaptop/Code/myproject/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/mylaptop/.nvm/versions/node/v16.9.1/bin/node
Arguments: /home/mylaptop/.yarn/lib/cli.js run android
Directory: /home/mylaptop/Code/myproject/packages/mobile
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
``` 

Not 100% sure thought if it still your package related your my system setup.

**Comment by ammarahm-ed** [comment]
@spatialvlad This is a different error, the monorepo issue seems to be fixed. So you need to put this in your app/build.gradle:

```groovy
android {
...
packagingOptions {
    pickFirst '**/*.so'
}
...
}
```
And it should build successfully. I don't get this error but it seems to happen for some people. Not sure still what project level configuration differences might be there compared to the example app.

**Comment by spatialvlad** [comment]
@ammarahm-ed , thanks! I confirm that adding these lines fixed it for me (though I did not need these lines before adding `react-native-mmkv-storage`).

Anyway, I've been really impressed with how quickly you resolved the issue. Great work! Thank you again.

**Comment by ammarahm-ed** [comment]
@spatialvlad The issue is that both `react-native` and `react-native-mmkv-storage` are building the same library. Ofcourse you wont get the error if `react-native-mmkv-storage` wasn't installed. However it does not happen in the example app. But I am investigating a fix.
