### ISSUE TITLE
[Bug] Library not building on Android with RN 0.66.0

### ISSUE THREAD

**Issue by enahum** [ammarahm-ed/react-native-mmkv-storage#167]
**Describe the bug**
After updating to RN 0.66.0 that released today library fails to build on Android (reanimated 2.3.0-beta.2 in used)

**Expected behavior**
Library builds successfully on Android with RN 0.66.0 

**Platform Information:**
 - OS: Android
 - React Native Version 0.66.0
 - Library Version 0.6.4

**Additional context**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-mmkv-storage:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Users/enahum/android/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/armeabi-v7a rnmmkv}
  ninja: Entering directory `/Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/.cxx/cmake/debug/armeabi-v7a'
  [1/37] Building CXX object core/CMakeFiles/core.dir/MMKV_OSX.cpp.o
  [2/37] Building CXX object core/CMakeFiles/core.dir/MMKVLog.cpp.o
  [3/37] Building CXX object core/CMakeFiles/core.dir/MiniPBCoder_OSX.cpp.o
  [4/37] Building CXX object core/CMakeFiles/core.dir/CodedInputDataCrypt_OSX.cpp.o
  [5/37] Building CXX object core/CMakeFiles/core.dir/CodedInputData_OSX.cpp.o
  [6/37] Building CXX object core/CMakeFiles/core.dir/PBUtility.cpp.o
  [7/37] Building CXX object core/CMakeFiles/core.dir/InterProcessLock.cpp.o
  [8/37] Building CXX object core/CMakeFiles/core.dir/MMBuffer.cpp.o
  [9/37] Building CXX object core/CMakeFiles/core.dir/KeyValueHolder.cpp.o
  [10/37] Building CXX object core/CMakeFiles/core.dir/MMKVLog_Android.cpp.o
  [11/37] Building CXX object core/CMakeFiles/core.dir/CodedOutputData.cpp.o
  [12/37] Building CXX object core/CMakeFiles/core.dir/CodedInputData.cpp.o
  [13/37] Building CXX object core/CMakeFiles/core.dir/CodedInputDataCrypt.cpp.o
  [14/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_md5_one.cpp.o
  [15/37] Building ASM object core/CMakeFiles/core.dir/aes/openssl/openssl_aesv8-armx.S.o
  [16/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_md5_dgst.cpp.o
  [17/37] Building ASM object core/CMakeFiles/core.dir/aes/openssl/openssl_aes-armv4.S.o
  [18/37] Building CXX object core/CMakeFiles/core.dir/MMKV_Android.cpp.o
  [19/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile_OSX.cpp.o
  [20/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile_Win32.cpp.o
  [21/37] Building CXX object core/CMakeFiles/core.dir/InterProcessLock_Win32.cpp.o
  [22/37] Building CXX object core/CMakeFiles/core.dir/ThreadLock_Win32.cpp.o
  [23/37] Building CXX object core/CMakeFiles/core.dir/InterProcessLock_Android.cpp.o
  [24/37] Building CXX object core/CMakeFiles/core.dir/ThreadLock.cpp.o
  [25/37] Building CXX object core/CMakeFiles/core.dir/aes/AESCrypt.cpp.o
  [26/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile.cpp.o
  [27/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_aes_core.cpp.o
  [28/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_cfb128.cpp.o
  [29/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile_Android.cpp.o
  [30/37] Building CXX object core/CMakeFiles/core.dir/MiniPBCoder.cpp.o
  [31/37] Building CXX object core/CMakeFiles/core.dir/crc32/zlib/crc32.cpp.o
  [32/37] Building CXX object core/CMakeFiles/core.dir/crc32/crc32_armv8.cpp.o
  [33/37] Building CXX object core/CMakeFiles/core.dir/MMKV.cpp.o
  [34/37] Building CXX object core/CMakeFiles/core.dir/MMKV_IO.cpp.o
  [35/37] Linking CXX static library core/libcore.a
  [36/37] Building CXX object CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o
  [37/37] Linking CXX shared library /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/build/intermediates/cmake/debug/obj/armeabi-v7a/librnmmkv.so
  FAILED: /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/build/intermediates/cmake/debug/obj/armeabi-v7a/librnmmkv.so 
  : && /Users/enahum/android/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi24 --gcc-toolchain=/Users/enahum/android/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/enahum/android/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fexceptions -frtti -std=c++1y -DONANDROID -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,librnmmkv.so -o /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/build/intermediates/cmake/debug/obj/armeabi-v7a/librnmmkv.so CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o -L/Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/build/react-native-0.66.0.aar/jni/armeabi-v7a -llog -lreactnativejni core/libcore.a -landroid /Users/enahum/android/ndk/21.4.7075529/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/arm-linux-androideabi/libz.a -latomic -lm && :
  /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi/jsi/jsi-inl.h:116: error: undefined reference to 'facebook::jsi::Value::~Value()'
  /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi/jsi/jsi-inl.h:116: error: undefined reference to 'facebook::jsi::Value::~Value()'
  /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:996: error: undefined reference to 'facebook::jsi::Value::~Value()'
  /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:991: error: undefined reference to 'facebook::jsi::Value::~Value()'
  /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi/jsi/jsi-inl.h:209: error: undefined reference to 'facebook::jsi::Value::~Value()'
  /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi/jsi/jsi-inl.h:209: error: undefined reference to 'facebook::jsi::Value::~Value()'
  /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi/jsi/jsi.h:970: error: undefined reference to 'facebook::jsi::Value::~Value()'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 54s

    at makeError (/Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/Users/enahum/Projects/go/src/github.com/mattermost/mattermost-mobile/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details
```

**Comment by ammarahm-ed** [comment]
I will investigate.

**Comment by yelanjri** [comment]
I have the  same issue, RN 0.66.0 using Cmake 3.18 and NDK version 23.0.7599858 
My stacktrace (NOT using reanimated)

>   [1/37] Building CXX object core/CMakeFiles/core.dir/MMKV_OSX.cpp.o
  [2/37] Building CXX object core/CMakeFiles/core.dir/MMKVLog_Android.cpp.o
  [3/37] Building CXX object core/CMakeFiles/core.dir/MMKVLog.cpp.o
  [4/37] Building CXX object core/CMakeFiles/core.dir/CodedInputDataCrypt_OSX.cpp.o
  [5/37] Building CXX object core/CMakeFiles/core.dir/CodedInputData.cpp.o
  [6/37] Building CXX object core/CMakeFiles/core.dir/CodedInputDataCrypt.cpp.o
  [7/37] Building CXX object core/CMakeFiles/core.dir/MMKV_Android.cpp.o
  [8/37] Building CXX object core/CMakeFiles/core.dir/MMKV.cpp.o
  [9/37] Building CXX object core/CMakeFiles/core.dir/KeyValueHolder.cpp.o
  [10/37] Building CXX object core/CMakeFiles/core.dir/CodedInputData_OSX.cpp.o
  [11/37] Building CXX object core/CMakeFiles/core.dir/CodedOutputData.cpp.o
  [12/37] Building CXX object core/CMakeFiles/core.dir/MMBuffer.cpp.o
  [13/37] Building CXX object core/CMakeFiles/core.dir/PBUtility.cpp.o
  [14/37] Building CXX object core/CMakeFiles/core.dir/MMKV_IO.cpp.o
  [15/37] Building CXX object core/CMakeFiles/core.dir/MiniPBCoder_OSX.cpp.o
  [16/37] Building CXX object core/CMakeFiles/core.dir/MiniPBCoder.cpp.o
  [17/37] Building CXX object core/CMakeFiles/core.dir/InterProcessLock.cpp.o
  [18/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile.cpp.o
  [19/37] Building CXX object core/CMakeFiles/core.dir/InterProcessLock_Win32.cpp.o
  [20/37] Building CXX object core/CMakeFiles/core.dir/InterProcessLock_Android.cpp.o
  [21/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile_Win32.cpp.o
  [22/37] Building CXX object core/CMakeFiles/core.dir/aes/AESCrypt.cpp.o
  [23/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile_Android.cpp.o
  [24/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_md5_one.cpp.o
  [25/37] Building CXX object core/CMakeFiles/core.dir/ThreadLock.cpp.o
  [26/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_md5_dgst.cpp.o
  [27/37] Building ASM object core/CMakeFiles/core.dir/aes/openssl/openssl_aesv8-armx.S.o
  [28/37] Building ASM object core/CMakeFiles/core.dir/aes/openssl/openssl_aes-armv4.S.o
  [29/37] Building CXX object core/CMakeFiles/core.dir/MemoryFile_OSX.cpp.o
  [30/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_aes_core.cpp.o
  [31/37] Building CXX object core/CMakeFiles/core.dir/ThreadLock_Win32.cpp.o
  [32/37] Building CXX object core/CMakeFiles/core.dir/aes/openssl/openssl_cfb128.cpp.o
  [33/37] Building CXX object core/CMakeFiles/core.dir/crc32/zlib/crc32.cpp.o
  [34/37] Building CXX object core/CMakeFiles/core.dir/crc32/crc32_armv8.cpp.o
  [35/37] Linking CXX static library core\libcore.a
  [36/37] Building CXX object CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o
  [37/37] Linking CXX shared library C:\dev\8470-ArgosSMG\ArgosMobileSMG\node_modules\react-native-mmkv-storage\android\build\intermediates\cmake\debug\obj\armeabi-v7a\librnmmkv.so
  FAILED: C:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/build/intermediates/cmake/debug/obj/armeabi-v7a/librnmmkv.so
  cmd.exe /C "cd . && C:\Users\younes.el.anjri\AppData\Local\Android\Sdk\ndk\23.0.7599858\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi24 --gcc-toolchain=C:/Users/younes.el.anjri/AppData/Local/Android/Sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/younes.el.anjri/AppData/Local/Android/Sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fexceptions -frtti -std=c++1y -DONANDROID -O0 -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,librnmmkv.so -o C:\dev\8470-ArgosSMG\ArgosMobileSMG\node_modules\react-native-mmkv-storage\android\build\intermediates\cmake\debug\obj\armeabi-v7a\librnmmkv.so CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o -LC:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/build/react-native-0.66.0.aar/jni/armeabi-v7a -llog  -lreactnativejni  core/libcore.a  -landroid  -lz  -latomic -lm && cd ."
  ld: error: undefined symbol: facebook::jsi::Value::~Value()
  >>> referenced by jsi-inl.h:116 (C:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi\jsi\jsi-inl.h:116)
  >>>               CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o:(void facebook::jsi::Object::setProperty<facebook::jsi::Function>(facebook::jsi::Runtime&, facebook::jsi::String const&, facebook::jsi::Function&&))
  >>> referenced by jsi-inl.h:116 (C:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi\jsi\jsi-inl.h:116)
  >>>               CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o:(void facebook::jsi::Object::setProperty<facebook::jsi::Function>(facebook::jsi::Runtime&, facebook::jsi::String const&, facebook::jsi::Function&&))
  >>> referenced by jsi-inl.h:209 (C:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi\jsi\jsi-inl.h:209)
  >>>               CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o:(void facebook::jsi::Array::setValueAtIndex<facebook::jsi::String&>(facebook::jsi::Runtime&, unsigned int, facebook::jsi::String&))
  >>> referenced 1 more times

  ld: error: undefined symbol: facebook::jsi::Value::~Value()
  >>> referenced by jsi.h:996 (C:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi\jsi\jsi.h:996)
  >>>               CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o:(facebook::jsi::Value::Value(facebook::jsi::Runtime&, facebook::jsi::Object const&))
  >>> referenced by jsi.h:991 (C:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi\jsi\jsi.h:991)
  >>>               CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o:(facebook::jsi::Value::Value(facebook::jsi::Runtime&, facebook::jsi::String const&))
  >>> referenced by jsi.h:970 (C:/dev/8470-ArgosSMG/ArgosMobileSMG/node_modules/react-native-mmkv-storage/android/../../../node_modules/react-native/ReactCommon/jsi\jsi\jsi.h:970)
  >>>               CMakeFiles/rnmmkv.dir/rnmmkv-adapter.cpp.o:(facebook::jsi::Value::Value<facebook::jsi::Array>(facebook::jsi::Array&&))
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by enahum** [comment]
@ammarahm-ed anything? I haven't been able to identify the source of the problem

**Comment by ammarahm-ed** [comment]
Fixed. update to v0.6.5
