### ISSUE TITLE
Task :app:compileDebugJavaWithJavac FAILED after changing MainApplicatiion.java

### ISSUE THREAD

**Issue by mateobou** [ammarahm-ed/react-native-mmkv-storage#94]
Hey !
I follow the steps to install mmkv-storage.

But when I modify the MainApplication.java and lauch `react-native run-android` I have got this error :

```
> Task :app:compileDebugJavaWithJavac FAILED
57 actionable tasks: 24 executed, 33 up-to-date
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
Note: /Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/node_modules/react-native-mmkv-storage/android/src/main/java/com/ammarahmed/mmkv/SecureKeystore.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/node_modules/react-native-mmkv-storage/android/src/main/java/com/ammarahmed/mmkv/RNMMKVModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/android/app/src/main/java/com/boxidy/MainApplication.java:39: error: cannot find symbol
          protected JSIModulePackage getJSIModulePackage() {
                    ^
  symbol: class JSIModulePackage
Note: /Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/android/app/src/debug/java/com/boxidy/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings
Note: /Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/node_modules/react-native-mmkv-storage/android/src/main/java/com/ammarahmed/mmkv/SecureKeystore.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/node_modules/react-native-mmkv-storage/android/src/main/java/com/ammarahmed/mmkv/RNMMKVModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/android/app/src/main/java/com/boxidy/MainApplication.java:39: error: cannot find symbol
          protected JSIModulePackage getJSIModulePackage() {
                    ^
  symbol: class JSIModulePackage
Note: /Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/android/app/src/debug/java/com/boxidy/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at makeError (/Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (/Users/mateoboukhobza/Documents/A2/BOÎTE À IDÉES/BoxidyContainer/Boxidy/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/usr/local/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
```

My MainApplication.java is here : 

```
package com.boxidy;
import android.app.Application;
import android.content.Context;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import com.ammarahmed.mmkv.RNMMKVJSIModulePackage; // <- add here

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

        // add this method to load our JSI Module.
          @Override
          protected JSIModulePackage getJSIModulePackage() {
              return new RNMMKVJSIModulePackage();
          }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.boxidy.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }
}

```

**Comment by hoanglam10499** [comment]
add `import com.facebook.react.bridge.JSIModulePackage;` 
after `import com.ammarahmed.mmkv.RNMMKVJSIModulePackage; // <- add here
`
