### ISSUE TITLE
Build failed because of NDK

### ISSUE THREAD

**Issue by harshal2030** [ammarahm-ed/react-native-mmkv-storage#99]
Tencent Docs states that that we need NDK r16b but build fails using this NDK.
I got the following error:
```
A problem occurred configuring project ':react-native-mmkv-storage'.
> Location specified by ndk.dir (C:UsersHarshalAppDataLocal\Android\Sdk\ndk\android-ndk-r16b) did not contain a valid NDK and and couldn't be used
```

**Comment by suhaildevzk** [comment]
still getting issue
`E/MMKV: <native-bridge.cpp:74::JNI_OnLoad> fail to locate fileID
2021-05-24 20:25:36.805 7417-7462/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.rntemplate, PID: 7417
    java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/com.rntemplate-BPRK4jp1e_KmvarhFbq75w==/base.apk!/lib/arm64-v8a/librnmmkv.so": -5
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.ammarahmed.mmkv.RNMMKVModule.<clinit>(Unknown Source:2)
        at com.ammarahmed.mmkv.a.c(Unknown Source:3)
        at com.facebook.react.t.a(Unknown Source:41)`
